id: /subscriptions/b1822850-b1dc-45bd-81e0-413650989eb8/resourceGroups/procguard-rg/providers/Microsoft.App/containerapps/procguard-api
identity:
  type: None
location: Sweden Central
name: procguard-api
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: procguard-api.livelyrock-e2ae864f.swedencentral.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8000
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries:
    - server: procguardacr.azurecr.io
      username: procguardacr
      passwordSecretRef: registry-password
    runtime: null
    secrets:
    - name: registry-password
    service: null
  customDomainVerificationId: 4052682A7974EEC145EAF15A67FC5A1F540D7FB4DD29B497A8E79AFFC0FDA012
  delegatedIdentities: []
  environmentId: /subscriptions/b1822850-b1dc-45bd-81e0-413650989eb8/resourceGroups/procguard-rg/providers/Microsoft.App/managedEnvironments/procguard-env
  eventStreamEndpoint: https://swedencentral.azurecontainerapps.dev/subscriptions/b1822850-b1dc-45bd-81e0-413650989eb8/resourceGroups/procguard-rg/containerApps/procguard-api/eventstream
  latestReadyRevisionName: procguard-api--f07jh9m
  latestRevisionFqdn: procguard-api--f07jh9m.livelyrock-e2ae864f.swedencentral.azurecontainerapps.io
  latestRevisionName: procguard-api--f07jh9m
  managedEnvironmentId: /subscriptions/b1822850-b1dc-45bd-81e0-413650989eb8/resourceGroups/procguard-rg/providers/Microsoft.App/managedEnvironments/procguard-env
  outboundIpAddresses:
  - 20.240.28.167
  - 20.240.28.184
  - 9.223.20.105
  - 135.116.6.186
  - 9.223.21.30
  - 9.223.218.210
  - 135.116.14.134
  - 9.223.143.243
  - 9.223.9.149
  - 74.241.137.85
  - 74.241.139.161
  - 74.241.138.64
  - 20.240.28.187
  - 74.241.136.237
  - 9.223.21.119
  - 9.223.10.153
  - 9.223.225.145
  - 9.223.220.233
  - 74.241.136.44
  - 9.223.87.134
  - 74.241.139.29
  - 9.223.20.250
  - 9.223.20.145
  - 20.240.29.51
  - 74.241.193.90
  - 74.241.192.157
  - 74.241.192.45
  - 74.241.193.154
  - 74.241.192.111
  - 74.241.193.34
  - 20.240.38.142
  - 20.240.38.235
  - 9.223.237.26
  - 9.223.246.165
  - 74.241.209.91
  - 74.241.211.241
  - 9.223.245.238
  - 135.116.14.86
  - 9.223.173.128
  - 9.223.237.22
  - 4.225.86.27
  - 9.223.75.69
  - 20.240.37.255
  - 9.223.245.208
  - 9.223.237.31
  - 9.223.45.114
  - 9.223.24.231
  - 74.241.210.170
  - 9.223.246.185
  - 9.223.16.144
  - 135.116.37.178
  - 9.223.247.36
  - 9.223.18.163
  - 20.240.37.231
  - 74.241.204.139
  - 74.241.204.246
  - 74.241.202.17
  - 74.241.200.59
  - 74.241.205.78
  - 74.241.203.192
  - 135.116.184.116
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: DATABASE_URL
        value: sqlite:///./procguard.db
      - name: AI_ENABLED
        value: 'true'
      - name: ENVIRONMENT
        value: production
      image: procguardacr.azurecr.io/procguard-api:latest
      name: procguard-api
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 10
      minReplicas: 1
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: Consumption
resourceGroup: procguard-rg
systemData:
  createdAt: '2026-01-09T22:44:08.8906196'
  createdBy: vijayavani1122@gmail.com
  createdByType: User
  lastModifiedAt: '2026-01-09T22:44:36.6692109'
  lastModifiedBy: vijayavani1122@gmail.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
