"""Add compliance tables and cross-link violations to filter audit

Revision ID: 018b20092120
Revises: 50c0dc4f3b9a
Create Date: 2026-01-08 21:09:00.709401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018b20092120'
down_revision: Union[str, None] = '50c0dc4f3b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_evidence',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('blob_path', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['compliance_reports.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'blob_path')
    )
    op.add_column('violations', sa.Column('triggering_filter_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'violations', 'filter_audit_logs', ['triggering_filter_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'triggering_filter_event_id')
    op.drop_table('compliance_evidence')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
