"""avg_add_resolved_to_violations_and_fix_status

Revision ID: 280c8abcaac7
Revises: 4f20a3c95a24
Create Date: 2026-01-07 11:55:46.674488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '280c8abcaac7'
down_revision: Union[str, None] = '4f20a3c95a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Surgical Add Resolved to Violations ###
    op.add_column('violations', sa.Column('resolved', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('violations_batch_id_fkey'), 'violations', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('idx_violations_batch_id'), 'violations', ['batch_id'], unique=False)
    op.alter_column('violations', 'rule',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('procedures', sa.Column('sequence_constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('required_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('approval_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('procedures', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('procedures', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('batches_procedure_id_procedure_version_fkey'), 'batches', 'procedures', ['procedure_id', 'procedure_version'], ['procedure_id', 'version'])
    op.alter_column('batches', 'current_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('batch_events_batch_id_fkey'), 'batch_events', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('one_approval_per_step'), 'batch_events', ['batch_id', sa.literal_column("(payload ->> 'step_id'::text)")], unique=True, postgresql_where="(event_type = 'approve_step'::text)")
    op.create_index(op.f('idx_batch_events_batch_id'), 'batch_events', ['batch_id'], unique=False)
    op.alter_column('batch_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('audit_logs_batch_id_fkey'), 'audit_logs', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('idx_audit_logs_batch_id'), 'audit_logs', ['batch_id'], unique=False)
    op.alter_column('audit_logs', 'actual_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'expected_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('batch_stage_events')
    op.drop_table('procedure_stages')
    # ### end Alembic commands ###
