"""Add OPA Audit Logs table

Revision ID: 3852e625e120
Revises: f37f22480b2e
Create Date: 2026-01-08 22:14:11.034124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3852e625e120'
down_revision: Union[str, None] = 'f37f22480b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opa_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('policy_package', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('result_hash', sa.String(), nullable=False),
    sa.Column('linked_violation_id', sa.UUID(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_violation_id'], ['violations.violation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opa_audit_logs')
    # ### end Alembic commands ###
