"""upgrade_audit_logs_to_canonical_model

Revision ID: 43c5c8efb425
Revises: 280c8abcaac7
Create Date: 2026-01-07 15:45:01.617360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c5c8efb425'
down_revision: Union[str, None] = '280c8abcaac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_stages',
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=False),
    sa.Column('procedure_version', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('expected_start', sa.Integer(), nullable=False),
    sa.Column('expected_end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('batch_stage_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_day', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['procedure_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('source', sa.String(), server_default='SYSTEM', nullable=False))
    op.add_column('audit_logs', sa.Column('project_id', sa.String(), server_default='Default Project', nullable=False))
    op.add_column('audit_logs', sa.Column('event_type', sa.String(), server_default='unknown', nullable=False))
    op.add_column('audit_logs', sa.Column('user_id', sa.String(), server_default='system', nullable=False))
    op.add_column('audit_logs', sa.Column('client_id', sa.String(), server_default='API', nullable=False))
    op.add_column('audit_logs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'SUCCESS'::character varying"))
    op.alter_column('audit_logs', 'batch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_audit_logs_batch_id', table_name='audit_logs')
    op.drop_constraint('audit_logs_batch_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'client')
    op.drop_column('audit_logs', 'project')
    op.drop_column('audit_logs', 'actual_state')
    op.drop_column('audit_logs', 'agent')
    op.drop_column('audit_logs', 'expected_state')
    op.drop_column('audit_logs', 'timestamp')
    op.alter_column('batch_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_batch_events_batch_id', table_name='batch_events')
    op.drop_index('one_approval_per_step', table_name='batch_events', postgresql_where="(event_type = 'approve_step'::text)")
    op.drop_constraint('batch_events_batch_id_fkey', 'batch_events', type_='foreignkey')
    op.alter_column('batches', 'current_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('batches_procedure_id_procedure_version_fkey', 'batches', type_='foreignkey')
    op.alter_column('procedures', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('procedures', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('procedures', 'sequence_constraints')
    op.drop_column('procedures', 'required_steps')
    op.drop_column('procedures', 'published_at')
    op.drop_column('procedures', 'approval_requirements')
    op.alter_column('violations', 'rule',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_violations_batch_id', table_name='violations')
    op.drop_constraint('violations_batch_id_fkey', 'violations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('violations_batch_id_fkey', 'violations', 'batches', ['batch_id'], ['batch_id'])
    op.create_index('idx_violations_batch_id', 'violations', ['batch_id'], unique=False)
    op.alter_column('violations', 'rule',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('procedures', sa.Column('approval_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('required_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('sequence_constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('procedures', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('procedures', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('batches_procedure_id_procedure_version_fkey', 'batches', 'procedures', ['procedure_id', 'procedure_version'], ['procedure_id', 'version'])
    op.alter_column('batches', 'current_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key('batch_events_batch_id_fkey', 'batch_events', 'batches', ['batch_id'], ['batch_id'])
    op.create_index('one_approval_per_step', 'batch_events', ['batch_id', sa.text("(payload ->> 'step_id'::text)")], unique=True, postgresql_where="(event_type = 'approve_step'::text)")
    op.create_index('idx_batch_events_batch_id', 'batch_events', ['batch_id'], unique=False)
    op.alter_column('batch_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('expected_state', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('agent', sa.VARCHAR(), server_default=sa.text("'PROCguard'::character varying"), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actual_state', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('project', sa.VARCHAR(), server_default=sa.text("'Default Project'::character varying"), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('client', sa.VARCHAR(), server_default=sa.text("'API'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key('audit_logs_batch_id_fkey', 'audit_logs', 'batches', ['batch_id'], ['batch_id'])
    op.create_index('idx_audit_logs_batch_id', 'audit_logs', ['batch_id'], unique=False)
    op.alter_column('audit_logs', 'batch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'SUCCESS'::character varying"))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('audit_logs', 'payload')
    op.drop_column('audit_logs', 'client_id')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'event_type')
    op.drop_column('audit_logs', 'project_id')
    op.drop_column('audit_logs', 'source')
    op.drop_column('audit_logs', 'created_at')
    op.drop_table('batch_stage_events')
    op.drop_table('procedure_stages')
    # ### end Alembic commands ###
