"""unify_metadata_and_add_project

Revision ID: 4f20a3c95a24
Revises: ef6ea0cb8d5c
Create Date: 2026-01-07 11:38:45.353216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f20a3c95a24'
down_revision: Union[str, None] = 'ef6ea0cb8d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Surgical Audit Log Migration ###
    
    # 1. Rename existing columns to match authoritative schema
    op.alter_column('audit_logs', 'audit_id', new_column_name='id')
    op.alter_column('audit_logs', 'occurred_at', new_column_name='timestamp')
    op.alter_column('audit_logs', 'attempted_event', new_column_name='action')
    op.alter_column('audit_logs', 'actual_outcome', new_column_name='actual_state')

    # 2. Add new authoritative fields with defaults (to handle existing rows safely)
    op.add_column('audit_logs', sa.Column('project', sa.String(), nullable=False, server_default='Default Project'))
    op.add_column('audit_logs', sa.Column('result', sa.String(), nullable=False, server_default='SUCCESS'))
    op.add_column('audit_logs', sa.Column('client', sa.String(), nullable=False, server_default='API'))
    op.add_column('audit_logs', sa.Column('agent', sa.String(), nullable=False, server_default='PROCguard'))

    # 3. Ensure constraints (optional, but good for cleanliness)
    # Re-apply non-nullable if needed or type changes, but renames preserve properties usually.
    # explicit casts if types changed (TEXT -> String is fine).
    
    # Note: We are IGNORING generated changes for procedures/batches to prevent data loss/regression.
    # We only care about Audit Log parity here.
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('violations_batch_id_fkey'), 'violations', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('idx_violations_batch_id'), 'violations', ['batch_id'], unique=False)
    op.alter_column('violations', 'rule',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('procedures', sa.Column('sequence_constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('approval_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('required_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('procedures', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('procedures', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('batches_procedure_id_procedure_version_fkey'), 'batches', 'procedures', ['procedure_id', 'procedure_version'], ['procedure_id', 'version'])
    op.alter_column('batches', 'current_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('batch_events_batch_id_fkey'), 'batch_events', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('one_approval_per_step'), 'batch_events', ['batch_id', sa.literal_column("(payload ->> 'step_id'::text)")], unique=True, postgresql_where="(event_type = 'approve_step'::text)")
    op.create_index(op.f('idx_batch_events_batch_id'), 'batch_events', ['batch_id'], unique=False)
    op.alter_column('batch_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('audit_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('attempted_event', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actual_outcome', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('audit_logs_batch_id_fkey'), 'audit_logs', 'batches', ['batch_id'], ['batch_id'])
    op.create_index(op.f('idx_audit_logs_batch_id'), 'audit_logs', ['batch_id'], unique=False)
    op.alter_column('audit_logs', 'expected_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'agent')
    op.drop_column('audit_logs', 'client')
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'actual_state')
    op.drop_column('audit_logs', 'project')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'id')
    op.drop_table('batch_stage_events')
    op.drop_table('procedure_stages')
    # ### end Alembic commands ###
