"""Add filter audit logs table with hash chaining support

Revision ID: 50c0dc4f3b9a
Revises: 522452346b87
Create Date: 2026-01-08 20:44:13.097219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c0dc4f3b9a'
down_revision: Union[str, None] = '522452346b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('screen', sa.String(), nullable=False),
    sa.Column('filter_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('approver_role', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED')", name='_approval_decision_check'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('batches', 'procedure_version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('procedures', 'locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('batches', 'procedure_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('approvals')
    op.drop_table('filter_audit_logs')
    # ### end Alembic commands ###
