"""Add locked column to procedures table

Revision ID: 679e4d7ad3a0
Revises: 6bb1174882fd
Create Date: 2026-01-07 19:23:20.107995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679e4d7ad3a0'
down_revision: Union[str, None] = '6bb1174882fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedures', 'locked')
    # ### end Alembic commands ###
