"""Implement new canonical schema

Revision ID: 6bb1174882fd
Revises: 43c5c8efb425
Create Date: 2026-01-07 17:45:43.011859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb1174882fd'
down_revision: Union[str, None] = '43c5c8efb425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually reordered and edited
    
    # 1. Drop foreign keys pointing to the old procedures table composite PK
    try:
        op.drop_constraint('batches_procedure_id_procedure_version_fkey', 'batches', type_='foreignkey')
    except Exception as e:
        print(f"Could not drop FK batches_procedure_id_procedure_version_fkey: {e}")


    # 2. Drop old tables that are no longer needed
    op.execute('DROP TABLE IF EXISTS batch_stage_events CASCADE')
    op.execute('DROP TABLE IF EXISTS procedure_stages CASCADE')
    op.execute('DROP TABLE IF EXISTS manufacturing_batches CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_requirements CASCADE')
    op.execute('DROP TABLE IF EXISTS batch_approvals CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_violations CASCADE')

    # 3. Alter procedures table to have a new PK
    op.alter_column('procedures', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('procedures', 'steps')
    op.drop_column('procedures', 'sequence_constraints')
    op.drop_column('procedures', 'approval_requirements')
    op.drop_column('procedures', 'published_at')
    op.drop_column('procedures', 'required_steps')

    # Drop the old composite primary key and create a new one.
    # Assuming the name is 'procedures_pkey'. If this fails, I'll need user intervention.
    try:
        op.execute('ALTER TABLE procedures DROP CONSTRAINT procedures_pkey')
    except Exception as e:
        print(f"Could not drop PK procedures_pkey: {e}")
        op.execute('ALTER TABLE procedures DROP CONSTRAINT pk_procedures')


    op.create_primary_key('procedures_pkey', 'procedures', ['procedure_id'])
    op.alter_column('procedures', 'version', primary_key=False, existing_type=sa.Integer(), nullable=False)
    
    # 4. Now create the new table that depends on procedures
    op.create_table('procedure_steps',
        sa.Column('step_id', sa.UUID(), nullable=False),
        sa.Column('procedure_id', sa.UUID(), nullable=False),
        sa.Column('step_order', sa.Integer(), nullable=False),
        sa.Column('step_name', sa.String(), nullable=False),
        sa.Column('requires_approval', sa.Boolean(), nullable=False),
        sa.Column('approver_role', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['procedure_id'], ['procedures.procedure_id'], ),
        sa.PrimaryKeyConstraint('step_id'),
        sa.UniqueConstraint('procedure_id', 'step_order', name='_procedure_step_order_uc')
    )

    # 5. Alter the rest of the tables
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'SYSTEM'::text"))
    op.alter_column('audit_logs', 'project_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'Default Project'::text"))
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'unknown'::text"))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'system'::text"))
    op.alter_column('audit_logs', 'client_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'API'::text"))
    op.alter_column('audit_logs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'SUCCESS'::character varying"))
    op.alter_column('audit_logs', 'batch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_audit_logs_batch_id', table_name='audit_logs')
    op.drop_column('audit_logs', 'project')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'expected_state')
    op.drop_column('audit_logs', 'actual_state')
    op.drop_column('audit_logs', 'agent')
    op.drop_column('audit_logs', 'client')

    op.alter_column('batch_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_batch_events_batch_id', table_name='batch_events')
    op.drop_index('one_approval_per_step', table_name='batch_events', postgresql_where="(event_type = 'approve_step'::text)")
    
    op.alter_column('batches', 'current_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('batches', 'procedure_version')
    op.create_foreign_key('fk_batches_procedure_id', 'batches', 'procedures', ['procedure_id'], ['procedure_id'])

    op.alter_column('violations', 'rule',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    try:
        op.drop_index('idx_violations_batch_id', table_name='violations')
    except Exception as e:
        print(f"Could not drop index idx_violations_batch_id: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # This downgrade is not fully supported, as it's a destructive migration.
    # A full restore would be needed from a backup.
    pass