"""Add boards table

Revision ID: 7369296e7da4
Revises: e5a98d320ccd
Create Date: 2026-01-09 12:07:47.099991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7369296e7da4'
down_revision: Union[str, None] = 'e5a98d320ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('primary_label', sa.String(), nullable=True),
    sa.Column('secondary_label', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_sync_checkpoints', 'committed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_sync_checkpoints', 'is_recovery_checkpoint',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_audit_sync_checkpoints_stream', table_name='audit_sync_checkpoints')
    op.create_index(op.f('ix_audit_sync_checkpoints_stream_name'), 'audit_sync_checkpoints', ['stream_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_sync_checkpoints_stream_name'), table_name='audit_sync_checkpoints')
    op.create_index('idx_audit_sync_checkpoints_stream', 'audit_sync_checkpoints', ['stream_name'], unique=False)
    op.alter_column('audit_sync_checkpoints', 'is_recovery_checkpoint',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('audit_sync_checkpoints', 'committed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('boards')
    # ### end Alembic commands ###
