"""Add SOP, Enforcement, and EvidenceChain tables

Revision ID: a9e48cc4b85e
Revises: 018b20092120
Create Date: 2026-01-08 21:35:00.617775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e48cc4b85e'
down_revision: Union[str, None] = '018b20092120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('immutable_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enforcement_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sop_rules',
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ),
    sa.PrimaryKeyConstraint('sop_id', 'rule_code')
    )
    op.create_table('enforcement_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_by', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.violation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_chain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.violation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('violations', sa.Column('sop_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'violations', 'sops', ['sop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'sop_id')
    op.drop_table('evidence_chain')
    op.drop_table('enforcement_events')
    op.drop_table('sop_rules')
    op.drop_table('enforcement_actions')
    op.drop_table('sops')
    # ### end Alembic commands ###
