"""Implement Cryptographic Chain of Custody

Revision ID: e5a98d320ccd
Revises: 3852e625e120
Create Date: 2026-01-08 22:25:43.541348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a98d320ccd'
down_revision: Union[str, None] = '3852e625e120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('audit_hash', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('violation_hash_link', sa.String(), nullable=True))
    
    # OPA Audit Logs: Handle non-nullable columns
    op.add_column('opa_audit_logs', sa.Column('decision_hash', sa.String(), nullable=True))
    op.add_column('opa_audit_logs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # No trigger on opa_audit_logs yet, but let's be safe if it exists
    op.execute("UPDATE opa_audit_logs SET decision_hash = 'legacy', payload = '{}'")
    op.alter_column('opa_audit_logs', 'decision_hash', nullable=False)
    op.alter_column('opa_audit_logs', 'payload', nullable=False)
    
    op.add_column('violations', sa.Column('violation_hash', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('opa_decision_hash', sa.String(), nullable=True))
    
    # Violations: Handle non-nullable column with trigger bypass
    op.add_column('violations', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("ALTER TABLE violations DISABLE TRIGGER ALL")
    op.execute("UPDATE violations SET payload = '{}'")
    op.execute("ALTER TABLE violations ENABLE TRIGGER ALL")
    op.alter_column('violations', 'payload', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'payload')
    op.drop_column('violations', 'opa_decision_hash')
    op.drop_column('violations', 'violation_hash')
    op.drop_column('opa_audit_logs', 'payload')
    op.drop_column('opa_audit_logs', 'decision_hash')
    op.drop_column('audit_logs', 'violation_hash_link')
    op.drop_column('audit_logs', 'audit_hash')
    # ### end Alembic commands ###
