"""Change audit_logs project_id to UUID

Revision ID: f37f22480b2e
Revises: a9e48cc4b85e
Create Date: 2026-01-08 21:46:35.974548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37f22480b2e'
down_revision: Union[str, None] = 'a9e48cc4b85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove old string default first
    op.execute("ALTER TABLE audit_logs ALTER COLUMN project_id DROP DEFAULT")
    
    op.alter_column('audit_logs', 'project_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='project_id::uuid')
               
    # Set new valid UUID default
    op.execute("ALTER TABLE audit_logs ALTER COLUMN project_id SET DEFAULT '550e8400-e29b-41d4-a716-446655440000'::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'Default Project'::text"))
    # ### end Alembic commands ###
