"""Add status field to Board model for soft-delete support

Revision ID: fe7a37137af0
Revises: 7369296e7da4
Create Date: 2026-01-09 12:38:50.021717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7a37137af0'
down_revision: Union[str, None] = '7369296e7da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual Addition: Create the boardstatus type first
    board_status = sa.Enum('ACTIVE', 'DEPRECATED', 'DELETED', name='boardstatus')
    board_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add as nullable
    op.add_column('boards', sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DELETED', name='boardstatus'), nullable=True))
    
    # Step 2: Update existing records
    op.execute("UPDATE boards SET status = 'ACTIVE' WHERE status IS NULL")
    
    # Step 3: Set NOT NULL
    op.alter_column('boards', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'status')
    # ### end Alembic commands ###

    # Manual Addition: Drop the boardstatus type
    sa.Enum(name='boardstatus').drop(op.get_bind(), checkfirst=True)
